framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'fresher@gothick.org.uk'

when@dev:
    framework:
        mailer:
            envelope:
                sender: 'fresher-dev@gothick.org.uk'
