version: '3.4'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: ChangeMe
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
